apiVersion: apps/v1
kind: Deployment
metadata:
  name: touchhle-trunk-builds
spec:
  replicas: 1
  selector:
    matchLabels:
      app: touchhle-trunk-builds
  template:
    metadata:
      labels:
        app: touchhle-trunk-builds
      annotations:
        instrumentation.opentelemetry.io/inject-sdk: "true"
    spec:
      containers:
        - name: touchhle-trunk-builds
          image: ghcr.io/dcnick3/touchhle-trunk-builds:ref-52200db8e4a5c041ed05b6bf4ccd3349b23a186e
          env:
            - name: CONFIG_GITHUB__TOKEN
              valueFrom:
                secretKeyRef:
                  name: touchhle-trunk-builds-secrets
                  key: github_token
