---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: touchhle-trunk-builds-secrets
  namespace: default
spec:
  encryptedData:
    github_token: AgCOYar21fLpCGxSu+eMpwrX31ADeutZi73xo/1wmCR3HTbo2y2GV4fitT8PKcVld1PnxVkESFk6Q/Z2aZbXO4nLcOrwOllMew4dcVC0QJT5ZW7i28HJWvghar0ItI4LA5e/OkHqaAS04BONVufakwfGsSFVJ7SzoDHg6M0ON8kufEeNMyJHkLACLJmosAr5C9IENGgCz7I1QENLwQgrDD7cQiW92iYDYD5Zn8NBlEU0cvBlJFMAeWtfht01fzemQh8yMyqssaxJ4IjdwgIf2biD/AzIfgfdMG5W9Fo9xyRH6PpPr8fpyxZ2fALU6FCejSpUw543ayinzujK6Qe+ulxnTPfJEtsfHHMF5zvRSx9juHYUHmriKpmEknriGQdsDdjmMjpyJyB4Tf7uI+4z9KGI2+B8eA2Js03Q3Pz461xvdROLojxrOEGU0umwLY/0fDzgx5pLv6CyyzK6hiD11Lq8Clf1NBCtVF85PCU8HjMSCG8LU1Dn08UguAP6MhEEwVwyISZbIjy6y0Tf2d+I1H6RpD7gIUGKRh+NW4gNfXe7v79cgJsiOlzJ0IKdK0TCjlvbXxNeH4C//kClIHIDZJthzg48botUdd5MTQgObdtna6eIL1m0ZyKPeV3Ui+ijyA+oYho/U30fEfomxPlaaDxlGLWoJCzQjcn2dsTK95mqYpIR6szMtZxaKEKmjnL70TglOmb8Rl/mQSpaWvFvNlAQd9Fft2gl28BlIZsFzwsKubV8DdNjGPL3
  template:
    metadata:
      creationTimestamp: null
      name: touchhle-trunk-builds-secrets
      namespace: default
    type: Opaque
